
services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=vibo'
      - 'POSTGRES_PASSWORD=Finytive@123'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5433:5432"

    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./docker/init-db:/docker-entrypoint-initdb.d

volumes:
  pgvector-data: